### ISSUE TITLE
Update to python3

### ISSUE THREAD

**Issue by joseims** [joseims/WhisperOutLoud#4]
**What:**
Update the code so you can use python3

**Why:**
Python2 will be descontinued in the future
**How:**
Run the bot with python3 and correct all the error's until no error is show. Also, be cautious about strings.

**Comment by cadengrey** [comment]
I'm on it

**Comment by RimorRes** [comment]
I'll help

**Comment by joseims** [comment]
Thanks all you guys! Merged @grug7 cause he was the only one that used the PR template!
